tmux-cssh: can use multiple pod filters (-p 2 -p 3) and some fixes

diff --git a/bin/tmux-cssh b/bin/tmux-cssh
--- a/bin/tmux-cssh
+++ b/bin/tmux-cssh
@@ -12,17 +12,29 @@ function fatal() {
     exit 1
 }
 
+function warn() {
+    echo "WARNING: $@" >&2
+}
+
 function phelp() {
     printf "%-15s\t%s\n" "$1" "$2"
 }
 
+# Sort first by data-center, then by Pod, then by server id
+function sort_hosts() {
+    sort -t '.' -k 3,3 -k 2,2 -k 1,1
+}
+
+HOSTLIMIT=10
 user_query=""
 query=()
 ssh_options=()
 do_log=0
 do_force=0
+do_dry_run=0
+pods=()
 
-while getopts ":r:p:q:l:LPvfh" opt; do
+while getopts ":r:p:q:l:LPvfnh" opt; do
     case $opt in
         L)
             do_log=1
@@ -31,10 +43,11 @@ while getopts ":r:p:q:l:LPvfh" opt; do
             query+="role:hg_$OPTARG"
             ;;
         p)
-            query+="zendesk_config_pod:$OPTARG"
+            #query+="zendesk_config_pod:$OPTARG"
+            pods+="$OPTARG"
             ;;
         P)
-            query+="chef_environment:production"
+            query+='chef_environment:*production*'
             ;;
         q)
             user_query="$OPTARG"
@@ -42,22 +55,29 @@ while getopts ":r:p:q:l:LPvfh" opt; do
         l)
             ssh_options+="-l$OPTARG"
             ;;
+        n)
+            do_dry_run=1
+            ;;
         v)
             ssh_options+="-v"
             ;;
         f)
             do_force=1
             ;;
+        n)
+            do_dry_run=1
+            ;;
         h)
             printf "Usage: $(basename $0) [-LPvh] [-p pod] [-q query] [-r role] [-l user] [host ...]\n"
             printf "NOTE: hostnames will be read from stdin when no arguments are specified.\n\n"
+            phelp "-n" "Dry run: Print the results of 'knife search', do not execute ssh"
             phelp "-l <user>" "Specifies the user to log in as on the remote machines"
             phelp "-L" "Capture each pane output to a file"
-            phelp "-p <pod>" "Search by Pod number"
-            phelp "-P" "Limit the search to production nodes"
+            phelp "-p <pod>" "Search by Pod number (can be specified multiple times)"
+            phelp "-P" "Limit the search to '*production*' nodes"
             phelp "-q <query>" "Specify a custom knife search query"
-            phelp "-r <role>" "Search by hostgroup role"
-            phelp "-f" "Force the command, even if it matches too many hosts"
+            phelp "-r <role>" "Search by hostgroup role (without the 'hg_' prefix)"
+            phelp "-f" "Suppress the error when more than $HOSTLIMIT hosts are matched"
             phelp "-v" "Run a verbose ssh session"
             phelp "-h" "Show this help"
             exit
@@ -77,7 +97,18 @@ hosts=()
 
 # Check for conflicting command line switches
 if [[ $#query > 0 && ! -z $user_query ]]; then
-    fatal "Can't specify a custom query together with filtering options"
+    fatal "Can't specify a custom query (-q) together with filtering options (-p -P -r)"
+fi
+
+# create filters for the selected POD(s)
+if [[ $#pods = 1 ]]; then
+    query+="zendesk_config_pod:$pods[1]"
+elif (( $#pods > 1 )); then
+    # to understand the following line search for ${^spec} in man zshexpn.
+    # Creates an array that contains (zendesk_config_pod:X zendesk_config_pod:Y ...).
+    local p=("zendesk_config_pod:"${^pods})
+    # then join the array with a OR and wrap the results in a subquery for knife.
+    query+="(${(j: OR :)p})"
 fi
 
 # Build our knife search query
@@ -90,6 +121,7 @@ elif [[ ! -z $user_query ]]; then
     hosts=($(knife search node -i "$user_query"))
 elif [[ $# == 0 ]]; then
     # reading hosts from stdin
+    warn "Reading server list from stdin"
     while read line; do
         hosts+=$line
     done
@@ -98,11 +130,16 @@ else
     hosts+=($@)
 fi
 
+if [[ $do_dry_run = 1 ]]; then
+    print ${(j:\n:)hosts} | sort_hosts
+    exit 0
+fi
+
 # Safety checks
 if [[ $#hosts = 0 ]]; then
     fatal "No hosts matched your query or knife command has failed"
-elif [[ $#hosts > 30 && $do_force = 0 ]]; then
-    fatal "More than 30 servers matched, please refine your search"
+elif (( $#hosts > $HOSTLIMIT )) && [[ $do_force = 0 ]]; then
+    fatal "Too many hosts matched ($#hosts); please refine your search query"
 fi
 
 SESSION="cssh-$$"
