some nice ssl functions from grml

diff --git a/zsh/zfunc b/zsh/zfunc
--- a/zsh/zfunc
+++ b/zsh/zfunc
@@ -84,15 +84,50 @@ return-limits(){
 
 # ansible mk-role
 mkrole() {
-	if [[ -z $1 ]]; then
-		echo "Usage: $(basename $0) <role name>"
-		exit 1
-	fi
-	if [[ ! -d roles ]]; then
-		echo "Missing 'roles' directory"
-		exit 1
-	fi
-	mkdir -p roles/$1/{tasks,handlers,templates,files,vars,defaults,meta}
+    if [[ -z $1 ]]; then
+	echo "Usage: $(basename $0) <role name>"
+	exit 1
+    fi
+    if [[ ! -d roles ]]; then
+	echo "Missing 'roles' directory"
+	exit 1
+    fi
+    mkdir -p roles/$1/{tasks,handlers,templates,files,vars,defaults,meta}
+}
+
+# from: grml
+ssl_hashes=( sha512 sha256 sha1 md5 )
+
+for sh in ${ssl_hashes}; do
+    eval 'ssl-cert-'${sh}'() {
+        emulate -L zsh
+        if [[ -z $1 ]] ; then
+            printf '\''usage: %s <file>\n'\'' "ssh-cert-'${sh}'"
+            return 1
+        fi
+        openssl x509 -noout -fingerprint -'${sh}' -in $1
+    }'
+done; unset sh
+
+ssl-cert-fingerprints() {
+    emulate -L zsh
+    local i
+    if [[ -z $1 ]] ; then
+        printf 'usage: ssl-cert-fingerprints <file>\n'
+        return 1
+    fi
+    for i in ${ssl_hashes}
+        do ssl-cert-$i $1;
+    done
+}
+
+ssl-cert-info() {
+    if [[ -z $1 ]]; then
+        echo "Usage: ssl-cert-info <file>"
+        exit 1
+    fi
+    openssl x509 -noout -text -in $1
+}
 }
 
 # vim: ft=zsh
